Day3

In [53]:
#Q1
import numpy as np
arr=np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [54]:
arr1=np.linspace(2,50,17)
arr1

array([ 2.,  5.,  8., 11., 14., 17., 20., 23., 26., 29., 32., 35., 38.,
       41., 44., 47., 50.])

In [55]:
#Q2
list1=[]
list2=[]
for i in range(5):
    num=int(input("enter values "))
    list1.append(num)
for i in range(5):
    num=int(input("enter values "))
    list2.append(num)
arr1=np.array(list1)
arr2=np.array(list2)
print("array 1 = ",arr1)
print("array 2 = ",arr2)
final=np.concatenate((arr1,arr2),axis=0)
print("final array = ",final)
print("sorted final array = ",sorted(final))

enter values 34
enter values 23
enter values 12
enter values 34
enter values 121
enter values 343
enter values 56
enter values 67
enter values 794
enter values 3
array 1 =  [ 34  23  12  34 121]
array 2 =  [343  56  67 794   3]
final array =  [ 34  23  12  34 121 343  56  67 794   3]
sorted final array =  [3, 12, 23, 34, 34, 56, 67, 121, 343, 794]


In [56]:
xx=np.array([[1,2,3],[4,6,5]])
yy=np.array([[7,8,9],[8,11,12]])
zz=np.concatenate((xx,yy),axis=None)
zz

array([ 1,  2,  3,  4,  6,  5,  7,  8,  9,  8, 11, 12])

In [57]:
#Q3
xx=np.array([[1,2,3],[4,6,5]])
yy=np.array([[7,8,9],[8,11,12]])
zz=np.concatenate((xx,yy),axis=0)
print(zz)
print("dimensions are ",zz.shape)
print("array size = ",zz.size)


[[ 1  2  3]
 [ 4  6  5]
 [ 7  8  9]
 [ 8 11 12]]
dimensions are  (4, 3)
array size =  12


In [58]:
x1=np.arange(4)
print(x1)
print(x1.shape)
print(type(x1))

[0 1 2 3]
(4,)
<class 'numpy.ndarray'>


# using np.reshape()

In [59]:
x2=x1.reshape((1, 4))
print(x1)
print('-----------------------------')
print(x1.shape)
print(x2)
print(x2.shape)
print('-----------------------------')
print("transpose of this matrix can be................")
print(x2.reshape((4, 1)))

[0 1 2 3]
-----------------------------
(4,)
[[0 1 2 3]]
(1, 4)
-----------------------------
transpose of this matrix can be................
[[0]
 [1]
 [2]
 [3]]


# Using np.expand_dims()

In [60]:
x3=np.expand_dims(x1, axis=0)
print(x1)
print(x1.shape)
print('-----------------------------')
print(x3)
print(x3.shape)
print('-----------------------------')
print(np.expand_dims(x1, axis=1))

[0 1 2 3]
(4,)
-----------------------------
[[0 1 2 3]]
(1, 4)
-----------------------------
[[0]
 [1]
 [2]
 [3]]



# using np.newaxis

In [61]:
print(x1)
print('-----------------------------')
print(x1[np.newaxis, :] )
print('-----------------------------')
print(x1[np.newaxis, :3])
print('-----------------------------')
print(x1[ :,np.newaxis])
print('-----------------------------')
print(x1[ 1:3,np.newaxis])

[0 1 2 3]
-----------------------------
[[0 1 2 3]]
-----------------------------
[[0 1 2]]
-----------------------------
[[0]
 [1]
 [2]
 [3]]
-----------------------------
[[1]
 [2]]


# Hstack/Vstack

In [62]:
#Q5
arr1=np.ones((4,4))
arr2=np.zeros((4,4))
print("-----HSTACKING----")
print(np.hstack((arr1,arr2)))
print("-----VSTACKING----")
print(np.vstack((arr1,arr2)))

-----HSTACKING----
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
-----VSTACKING----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [63]:
#Q6
a=np.array([11,11,22,22,33,33])
np.unique(a, return_counts=True)


(array([11, 22, 33]), array([2, 2, 2], dtype=int64))

In [64]:
eye=np.identity(4)
print(eye)
print("------------------")
print(eye[0:2,0:2])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------
[[1. 0.]
 [0. 1.]]
